# Generated by Django 5.0.6 on 2024-05-09 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='num_of_book',
            new_name='quantity',
        ),
    ]
