# Generated by Django 5.0.6 on 2024-05-10 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='borrowDate',
            new_name='wishlistDate',
        ),
    ]
